### ISSUE TITLE
授权时出现运行时异常，无法启动授权Activity

### ISSUE THREAD

**Issue by AlexMofer** [box/box-android-sdk#387] opened 2019-02-16 08:33 UTC
### 错误日志
```
2019-02-16 15:44:52.921 18529-18529/***.***.*** E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ***.***.***, PID: 18529
    java.lang.RuntimeException: Unable to start activity ComponentInfo{***.***.***/com.box.androidsdk.content.auth.OAuthActivity}: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class com.box.androidsdk.content.auth.OAuthWebView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class com.box.androidsdk.content.auth.OAuthWebView
     Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class com.box.androidsdk.content.auth.OAuthWebView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:420)
        at android.app.Activity.setContentView(Activity.java:2772)
        at com.box.androidsdk.content.auth.OAuthActivity.onCreate(OAuthActivity.java:114)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
        at xw.b(SourceFile:99)
        at xw.b(SourceFile:174)
        at xw.a(SourceFile:155)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(SourceFile:236)
        at com.android.webview.chromium.WebViewChromium.init(SourceFile:45)
        at android.webkit.WebView.<init>(WebView.java:422)
2019-02-16 15:44:52.921 18529-18529/***.***.*** E/AndroidRuntime:     at android.webkit.WebView.<init>(WebView.java:348)
        at android.webkit.WebView.<init>(WebView.java:331)
        at android.webkit.WebView.<init>(WebView.java:318)
        at com.box.androidsdk.content.auth.OAuthWebView.<init>(OAuthWebView.java:59)
        	... 28 more
```

### 出现情况
非必现，偶发，且Android 8.0（API 27）及Android 9.0（API 28）均有触发。

### 原因猜测
具体原因未知，但可能与多进程相关，应用对象为一款多进程APP。

**Comment by nidoran** [comment] 2019-03-19 23:57
From Google Translate:

Title: A runtime exception occurred during authorization, and the authorization activity could not be started #387

Error log
\<stacktrace\>

Situation
Not necessarily, occasional, and Android 8.0 (API 27) and Android 9.0 (API 28) are triggered.

Reason guess
The specific reason is unknown, but it may be related to multiple processes. The application object is a multi-process APP.

**Comment by lukasvalkovic** [comment] 2019-03-22 13:24
@AlexMofer I was not able to reproduce your issue. Can you please, provide minimal buildable reference project to us? 

As you can see in chromium issue tracker https://crbug.com/558377 it is not recommended to use WebView in more processes and you should instead change your code to use WebView only from one process.

**Comment by AlexMofer** [comment] 2019-03-28 07:20
@lukasvalkovic 
我自己也无法重现该问题，至少现在未找到必现方式。查阅了一些资料，貌似是WebView自身的问题，该问题仅在多进程APP中出现，好象是WebView使用的缓存文件，在不同进程中文件被进程锁定而导致WebView创建失败。应用其实并不会在多个进程中同时使用WebView，而且WebView使用也尽量在同一个进程之中。

**Comment by nidoran** [comment] 2019-03-28 23:11
From Google Translate:

I can't reproduce the problem myself, at least not now. Checked some information, it seems to be a problem of WebView itself, this problem only appears in the multi-process APP, it seems to be the cache file used by WebView, the file is locked by the process in different processes and the WebView creation fails. Applications do not use WebView in multiple processes at the same time, and WebView is also used in the same process.

**Comment by nidoran** [comment] 2019-03-28 23:11
Closing this issue

**Closed by nidoran** 2019-03-28 23:11 UTC
