### ISSUE TITLE
Function ENABLE_BOX_APP_AUTHENTICATION set "true" not working

### ISSUE THREAD

**Issue by ProFive** [box/box-android-sdk#227] opened 2017-01-01 16:20 UTC
I ready installed box client form google play store.
 In my application, I set configure client:

```
BoxConfig.IS_LOG_ENABLED = true;
BoxConfig.IS_DEBUG = true;
BoxConfig.CLIENT_ID = "97ubtwxxxxxxxxxxxxxxxxxxxx338cye";
BoxConfig.CLIENT_SECRET = "P9kxxxxxxxxxxxxxxxxxxxdMago9w";
BoxConfig.REDIRECT_URL = "http://localhost";
BoxConfig.ENABLE_BOX_APP_AUTHENTICATION = true;
```

After that, I create a BoxSession and authenticate:

```
 mSession = new BoxSession(this); 
 mSession.setSessionAuthListener(this);
 mSession.authenticate(this);
```

when run my application, it call open account box client page(Box installed from Google play store) with your account logged in. I clicked on this my account then it change to login page.  I login agian with my account then the result is "An unknown error has occurred - try again later.If you continue to experience problems, email android-support@box.com"
1. Please help me find this problem?
2. I think when did  I click my account at account page then it must log-in in my application but it go to login page?

**Comment by doncung** [comment] 2017-01-07 01:55
Thanks I've tried this flow, and I believe the issue is the "http://localhost". I believe it will still allow you to login, but the webview logic we have receives an exception from the OS as the page doesn't exist. 
If you have your own web page you can set the redirect url to that or you can use the default. 
You will need to set a corresponding redirect on the developer page however (developers.box.com).

2. The ENABLE_BOX_APP_AUTHENTICATION functionality is meant to be used with api keys that have been granted child access rights. In this ideal flow, the user only needs to click on the grant access button if they have the official box application installed and logged in. The flow with a normal api key is it helps fill in the user email address if a user wants to login to an existing account. It looks like there may be a bug in this logic so it is filling in the username instead.

**Comment by doncung** [comment] 2017-01-25 21:41
Closing for now. Let me know if you are still seeing this after changing the host.

**Closed by doncung** 2017-01-25 21:41 UTC
