### ISSUE TITLE
onAuthCreate() invoked multiple times after BoxSession.authenticate() invoked

### ISSUE THREAD

**Issue by paragchandra** [box/box-android-sdk#225] opened 2016-12-29 20:49 UTC
I've observed that this callback is invoked multiple times for each authenticate() call, which is causing problems for my application. This problem is reproducible in the box-content-sample app, on the master branch: simply set a breakpoint in MainActivity.onAuthCreated(), then debug the app and proceed to login. You will hit the breakpoint between 2-4 times, and moreover, the contents of the root folder will be repeated 2-4 times in the MainActivity.

I've reproduced this on the following:

Nexus 6, running Android 6.0.1
x86 emulator, running Android 6.0
x86 emulator, running Android 4.4

**Comment by nikz-dev** [comment] 2017-01-05 14:00
Same issue occur with my app. 
After calling mSession.authenticate();
    public void onAuthCreated(BoxAuthentication.BoxAuthenticationInfo info) called more than once. 


Nexus 5X, running Android 7.1.1

**Comment by doncung** [comment] 2017-01-07 01:23
Thanks. Can you let me know how you are hitting 4 times? After looking into this looks like we are calling onAuthCreated from the session twice on login, once from BoxAuthentication and then once from the AuthCreationRequest. I'll fix this shortly, but wanted to see if you had a method to reproduce 4 calls (I'm just getting 2)

**Comment by paragchandra** [comment] 2017-01-09 20:54
I got the root folder to display 3x just now, simply by adding an account, logging out, and then adding back that same account. However, logging out and then back in again only resulted in 2x duplication. Doesn't seem consistent. I tried most recently on x86 emulator, running Android 6.0

**Comment by doncung** [comment] 2017-01-09 23:42
Thanks. The 2x is normal with the current bug. After some digging it looks like the sample is managing 2 sessions with mOldSession and mSession so I believe the other calls are from mOldSession. I'll update the sample to make it clearer.

**Comment by doncung** [comment] 2017-01-10 02:15
So I think I've solved this issue here:
https://github.com/box/box-android-sdk/pull/234
Once one of my coworkers approve we'll merge this in and update our maven.

**Comment by paragchandra** [comment] 2017-01-27 13:50
This appears to be fixed.

**Comment by paragchandra** [comment] 2017-01-27 13:51
Actually, I just realized I made a change to the sample app that would mask the problem even if it hadn't been fixed. So, can you please confirm that this has been merged in and then I will verify it?

**Comment by doncung** [comment] 2017-01-31 19:44
It should be fixed now. There was a change required in the sample as well to remove the listener for the old session.

**Closed** 2017-02-13 21:20 UTC
